// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CustomIndexData struct {
	TableName  string `json:"tableName"`
	ColumnName string `json:"columnName"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type QueryData struct {
	TableName  string `json:"tableName"`
	ColumnName string `json:"columnName"`
	Condition  string `json:"condition"`
	Value      string `json:"value"`
}

type ReadAllTableData struct {
	TableName string `json:"tableName"`
}

type TableData struct {
	Instruction string `json:"instruction"`
	TableName   string `json:"tableName"`
	PrimaryKey  string `json:"primaryKey"`
}

type TableRowData struct {
	TableName string `json:"tableName"`
	JSONStr   string `json:"jsonStr"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type DeleteTableData struct {
	TableName string `json:"tableName"`
}

type UpdateTableName struct {
	OldTableName string `json:"oldTableName"`
	NewTableName string `json:"newTableName"`
}
